### ISSUE TITLE
Repeated Ticker/Registration requests at registrars from registrants who already have existing registrations

### ISSUE THREAD

**Issue by oascigil** [datahop/p2p-service-discovery#2]
In the "SPAM" mode of registration (i.e.,remove ticket after registration), many registrars receive ticket requests from registrants that have already registered for the same topic. 

Investigate the reason. A possible solution is to use a priority queue in the routing table lookups in order to return the least-recently used neighbors.

**Comment by srene** [comment]
This issue has been solved by avoiding sending ticket requests to those nodes with already ongoing registrations
